language: python
sudo: false
python:
    - 3.5
    - 3.4
env:
    - JHUB_VERSION=master
    - JHUB_VERSION=latest # latest released version

before_install:
    - npm install
    - npm install -g configurable-http-proxy
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install: ./build_tools/travis/install.sh

script:
    - nose2 -v

# Make travis quiet
notifications:
  email: false
