language: python

# Needed so we can spawn docker containers
sudo: required
services:
    - docker
addons:
  apt:
    packages:
    - build-essential
python:
  - 3.4
  - 3.5
env:
  - JHUB_VERSION=master
  - JHUB_VERSION=latest # latest released version

before_install:
  # XXX remove IPv6 entry via https://github.com/travis-ci/travis-ci/issues/4978
  - sudo [ $(ip addr show | grep "inet6 ::1" | wc -l) -lt "1" ] && sudo sed -i '/^::1/d' /etc/hosts
  - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
  - export UPLOADDIR=${HOME}/frontend-test-screenshots/${JHUB_VERSION}_${TRAVIS_PYTHON_VERSION}
  - make gistup

  # some DEBUG information
  # XXX the next two are related to the IPv6 hack above
  - cat /etc/hosts
  - ifconfig
  - which python
  - pip --version
  - pip freeze
  - npm list
  - ls -alR $HOME/frontend-test-screenshots/

install: 
  - npm install -g configurable-http-proxy
  - export PIP_OPTIONS="-f ~/travis-wheels/wheelhouse"
  - ./build_tools/install.sh

script:
  - nose2 -v --start-dir everware # unit tests live in everware/
  - ./build_tools/test_frontend.sh
  - prefix="build $TRAVIS_JOB_NUMBER"
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] ; then prefix+=" PR $TRAVIS_PULL_REQUEST " ; fi
  - make upload_screens -e M="$prefix travis-CI screens ($JHUB_VERSION $TRAVIS_PYTHON_VERSION)"

cache:
    apt: true
    directories:
     - $HOME/.cache/pip
     - $HOME/frontend-test-screenshots/

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/778f542a122b7dd8c0f3
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always   
