language: python

# Needed so we can spawn docker containers
sudo: required
services:
    - docker
addons:
  apt:
    packages:
    - build-essential
python:
    - 3.5
# commented out for testing speed-up sake
#     - 3.4
# env:
#     - JHUB_VERSION=master
#     - JHUB_VERSION=latest # latest released version

before_install:
  - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
  # print DEBUG information
  - make install
  - npm install -g gistup
  # some DEBUG information
  - set -e
  - which python
  - echo $LD_LIBRARY_PATH

install: 
  - make install
  - make run-test-server
# - ./build_tools/travis/install.sh

script:
#  - nose2 -v --start-dir everware # unit tests live in everware/
#  - ./build_tools/travis/test_frontend.sh
  - make test-client || FAIL=1
  - make stop
  - make upload_screens
  - cat everware.log
  - exit $FAIL
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/778f542a122b7dd8c0f3
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always   
